"""add_is_default_to_tours

Revision ID: da032fae2250
Revises: 6bfb8c5aa4a3
Create Date: 2026-06-13 10:16:05.615439
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da032fae2250'
down_revision: Union[str, None] = '6bfb8c5aa4a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('is_default', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tours', 'is_default')
    # ### end Alembic commands ###
